version: "3"
services:
  postgres:
    image: postgres:10.7
    ports:
    - "5432:5432"
    environment:
    - "POSTGRES_PASSWORD:dalong"
    volumes:
    - ./db_data:/var/lib/postgresql/data
  backup:
    image: dalongrong/pg-dump
    environment: 
    - "PG_HOST=postgres"
    - "PG_DB=postgres"
    - "PG_PASSWORD=dalong"
    - "S3_HOST=s3:9000"
    - "S3_ACCESS_KEY=dalongdemo"
    - "S3_SECRET_KEY=dalongdemo"
    - "S3_PROTOCOL=http"
  s3:
    image: minio/minio
    command: server /export
    ports:
    - "9000:9000"
    volumes:
      - ./data:/export
      - ./config:/root/.minio
    environment:
    - "MINIO_ACCESS_KEY=dalongdemo"
    - "MINIO_SECRET_KEY=dalongdemo"